### PR TITLE
fix: set sentAt to send time

### LINKED ISSUE #25: BUG : timestamp is always equals to receivedAt
Here https://github.com/rudderlabs/analytics-go/commit/f2618e080e43119e258a4dd8c4f5affd94492908 you replaced `Timestamp` with `OriginalTimestamp` and `SentAt`. But `SentAt` always gets overwritten by `OriginalTimestamp` because of this code:

```go
m.OriginalTimestamp = makeTimestamp(m.OriginalTimestamp, ts)
m.SentAt = m.OriginalTimestamp
```

According to [documentation](https://www.rudderstack.com/docs/event-spec/standard-events/common-fields/#sdk-sources) `timestamp` is calculated on server side using this formula `timestamp = receivedAt - (sentAt - originalTimestamp)`. 

Because in current code `OriginalTimestamp = SentAt`, `timestamp` on server side results in `receivedAt`. i.e. `OriginalTimestamp` and `SentAt` from SDK are ignored.

### PR DESCRIPTION
**Pull request by rhino1998**
# Description

When `timestamp` is not specified, `timestamp` is computed as `timestamp = receivedAt - (sentAt - originalTimestamp)`. Currently this is handled incorrectly as `sentAt` was set to the same value `originalTimestamp` causing the computed `timestamp` to be `receivedAt`. Manually setting `originalTimestamp` was not functional as `sentAt` was still set to that value.

This PR makes the following changes
* Sets `sentAt` at batch-send time rather than at message-enqueue time so that the remote skew calculation works

This fixes #25 

## Summary by CodeRabbit

- **New Features**
	- Enhanced message sending functionality with timestamp tracking for improved message delivery reliability.
	- Introduced a method to update the `SentAt` timestamp for various message types, streamlining message management.

- **Bug Fixes**
	- Added error handling and notifications for failed message deliveries, ensuring better observability and reliability of the message-sending process. 

- **Chores**
	- Updated test data to reflect changes in timestamp handling for message events.

### CODE REVIEW

File: analytics.go [hunk 1]
```diff
@@ -190,7 +190,6 @@ func (c *client) Enqueue(msg Message) (err error) {
 		m.Type = "alias"
 		m.MessageId = makeMessageId(m.MessageId, id)
 		m.OriginalTimestamp = makeTimestamp(m.OriginalTimestamp, ts)
-		m.SentAt = m.OriginalTimestamp
```
Comment (saikumarrs) [inline analytics.go:193]: Let's still set the SentAt to the original timestamp to help in payload size calculation before finalizing the events for the batch.

File: message.go [hunk 2]
```diff
@@ -83,6 +84,40 @@ func (m message) MarshalJSON() ([]byte, error) {
...
+	default:
+		err = fmt.Errorf("messages with custom types cannot be enqueued: %T", msg)
+		return
+	}
+
+	if m.json, err = json.Marshal(m.msg); err == nil {
+		if len(m.json) > maxBytes {
+			err = ErrMessageTooBig
+		}
+	}
```
Comment (saikumarrs) [inline message.go:117]: We can avoid this like I mentioned in the other mentioned.

**Review by saikumarrs — CHANGES_REQUESTED** [review]

File: analytics.go (hunk 1 above)
Comment (rhino1998) [reply analytics.go]: I made the requested changes [666ce95](https://github.com/rudderlabs/analytics-go/pull/27/commits/666ce9581f7e1cf64de68864dd50eeceb30407d0)

File: message.go (hunk 2 above)
Comment (rhino1998) [reply message.go]: I made the requested changes [666ce95](https://github.com/rudderlabs/analytics-go/pull/27/commits/666ce9581f7e1cf64de68864dd50eeceb30407d0)

**Comment by saikumarrs** [comment]
@coderabbitai full review

**Review by saikumarrs — APPROVED** [review]
